#!/usr/bin/env bash

if [ -f rechoid ]; then
  echo "start existing redis container"
  docker start $(cat rechoid)
  exit 0
fi

echo "create new redis container"
docker run -p 6379:6379 -d redis > rechoid
cat rechoid
